### ISSUE TITLE
Indicate stale keys via `key_out` or `exchange_command`

### ISSUE THREAD

**Issue by stv0g** [rosenpass/rosenpass#85]
Currently, there seems to be no way of detection when a key became stale.

We appear to simply write a random key to the file:

https://github.com/rosenpass/rosenpass/blob/397a776c55b1feae1e8e5aceef01cf06bf56b6ed/src/app_server.rs#L534

**Comment by koraa** [comment]
Yup, with the stale tag:

https://github.com/rosenpass/rosenpass/blob/397a776c55b1feae1e8e5aceef01cf06bf56b6ed/src/app_server.rs#L617

The format of the output is:

    output-key peer {} key-file {of:?} {why}

Fields 1, 2, and 4 are static. Field 3 contains the peer id, field 5 the output file used.

Field six is the tag indicating why the key was written. Why is defined by:

```
            let why = match why {
                KeyOutputReason::Exchanged => "exchanged",
                KeyOutputReason::Stale => "stale",
            };
```

So field six is either "stale" for "erasing the key" or "exchanged" for "there is a new key". This design is very deliberate: The simplest way to use this is to just always read the key on every output. Reading the `why` field is extra work; most applications should disregard the why tag **unless they explicitly implement a zeroization function for their internal key** or they wish to implement a **status indicator that the connection is down**.

Under no circumstance must the stale tag be used to extend the life of a stale key, because this renders the key renegotiation mechanism insecure. Consider this attack:

The threat scenario that key renegotiation threat scenario is an attacker who:

* Can access the output keys
* But only infrequently

In cryptography we could model this by giving the attacker access to what is called an oracle; i.e. a black-box function that returns the key under some conditions

* We introduce a output-key oracle `GetKey` and an security parameter `GetKeyCost` that places a limit on the frequency the attacker can call this oracle.
* We also introduce the security parameter `KeyRenegotiationFrequency`

Lets assume the stale tag is used incorrectly; i.e. it is ignored. With the `GetKey` oracle the attacker can now use the following attack:

1. Invoke the `GetKey` oracle once to acquire `osk_1`
2. Perform a man in the middle attack that selectively drops all key-renegotiation packets but allows data packets to pass through.

In this scenario the entire plain text transmitted is leaked, because key-renegotiation never occurs.

Lets assume the same attack is used with active key renegotiation; then the man in the middle attack will simply disconnect the connection between both parties. This is an ability (dropping packages) that the adversary already had so no extra abilities are gained.

The attacker could still use the `GetKey` oracle, but this would only yield two or three-minute blocks of data at a time. If the `GetKeyCost` and `KeyNegotiationFrequency` security parameters are sufficiently high, the attackers gains almost no information.

In cryptographic terms I would say that the attackers advantage is $\frac{1}{\texttt{GetKeyCost} \texttt{KeyNegotiationFrequency}$. The attacker has linear "advantage" (cryptographic term) trying to get gain information about the plain text. Linear because the equation is linear (contains no exponentiation terms).

## Practical case

This scenario is not entirely unrealistic. Consider the scenario of Rosenpass being used to secure a VPN between two data centers. The asymmetric protocol could be run in an HSM (hardware security module) but for performance reasons you might still do the actual data encryption on a server.

A state actor could use zero-day exploits to break into the server and read the memory. The cost here is that the more data they extract, the higher the risk of being detected.

Exfiltrating a single key may be undetected, but exfiltrating a key every two minutes might be more noticeable because the exploit can not be wiped from the devices

## Conclusion

Please keep these sorts of attacks in mind when fiddeling with stale keys. Please close the issue if this explanation was satisfactory.

**Comment by stv0g** [comment]
Hi @koraa,
thanks for the detailed explanation.

I am currently using the keyout file only for interoperability testing of my Go against the Rust reference implementation.

The source of my problem lies in the fact that I am only observing the keyout file via inotify and ignore rosenpass standard output. I have not considered to to parse the standard output yet because I considered it as log output rather than part of the IPC interface. But on a second look, I realize that stdout is actually well defined and I should parse it too...
Is there any reason you do not output the OSK via stdout as well?

In my opinion, having the OSK written to a file carries a higher risk to be misused (e.g. writing to persistent FS, rather then memory backed VFS). And it simplifies the IPC interface..

Looking at the upcoming socket interface, I could imagine that it could look a lot similar to the stdout output but includes the OSKs.

The GitHub issue has been created mainly for starting a discussion about it. Please dont see this as a request to fix this. I know you are over the top busy with managing tasks and research proposals 😃 
I am just curious to learn about the plans and find some ways to contribute to rosenpass (may it be architecturally or via code).

**Comment by koraa** [comment]
>  Is there any reason you do not output the OSK via stdout as well?

Because there is a risk your key would land in a log file and it couldn't be erased.

> Looking at the upcoming socket interface, I could imagine that it could look a lot similar to the stdout output but includes the OSKs.

Exactly!

>  I am just curious to learn about the plans and find some ways to contribute to rosenpass (may it be architecturally or via code).

Do you have a matrix account? I think the first step is to join our internal matrix channel :D

**Comment by koraa** [comment]
> Yes my Matrix account is [stv0ge@matrix.org](mailto:stv0ge@matrix.org)

You have an invite!

**Comment by koraa** [comment]
@stv0g Can we close this?

**Comment by stv0g** [comment]
Yes, I think this is better discussed in #95
