### ISSUE TITLE
Remove `exchange_command` option until implemented

### ISSUE THREAD

**Issue by stv0g** [rosenpass/rosenpass#86]
Maybe I am missing something, but it appears to be that the option is parsed, but never used:

https://github.com/search?q=repo%3Arosenpass%2Frosenpass%20exchange_command&type=code

**Comment by koraa** [comment]
Have you tried it out? There was a big PR that turned out to be half-done; wouldn't be the first new UX feature that is unimplemented…

The entire situation is a unfortunate and a bit of a drain on me right now; we have some bigger UX changes (operation over unix sockets) planned but these are blocked by grant applications.

Not sure how to proceed with that, thank you for the UX work.

**Comment by stv0g** [comment]
Yes, its parsed correctly. The option is also used on the example configs. But it does not appear to have any effect.

I propose to remove it from the example configs, man page and documentation for now an re-add it once the feature is implemented.

**Comment by stv0g** [comment]
A little update: go-rosenpass now supports both the `wireguard` and `exchange_command` options via the configuration file and CLI interface. The latter only supports the `wireguard` setting.

**Comment by koraa** [comment]
That is wonderful! did you consider which user will be able to edit the config file and which user go-rosenpass will run as?

**Comment by koraa** [comment]
Fixed in 31d43accd5f5671e4bd7b7ee2b6e7e1af964258a
