### ISSUE TITLE
Perform CI tests without Nix

### ISSUE THREAD

**Issue by emilengler** [rosenpass/rosenpass#98]
While Nix is all fun and games, I truly believe that we should also add some CI tests that build and run the Rosenpass tests without Nix, for the people who do not or cannot use (looking at you BSD) the Nix package manager.

This could have prevented #96 for example.

**Comment by wucke13** [comment]
I get your point, but #96 indeed is an issue in the Nix dev environment providing fake cmake to the devshell. You only ran into this because you where using the nix devshell, someone using rustup and cargo would not have triggered this.

What I would propose instead however would be that we have `nix develop  --command cargo test` in one unit test, to verify that the devShell works.

Other than that [we already have a lightweight non-Nix test workflow](https://github.com/rosenpass/rosenpass/blob/main/.github/workflows/qc.yaml), adding a `cargo test` there wouldn't hurt, but would not have uncovered this bug either.
